
[destination.snowflake.credentials]
database = "Jobtech_analysis"
username = "Dlt_role"
password = "login12345" # please set me up!
host = "MZQPYFK-EF49460" # please set me up!  
warehouse = "job_analysis_wh"
role = "jobtech_dlt_role"