sources:
    - name: jobtech_analysis
      schema: staging
      tables:
        - name: stg_job
          identifier: job_ads
          metadata:
            dagster:
              asset_key: ['dlt_jobads_source_jobsearch_resource']