sources:
    - name: jobtech_analysis
      schema: staging
      tables:
        - name: stg_ads
          identifier: job_ads
          metadata:
            dagster:
              asset_key: ['dlt_jobads_source_jobads_resource']